---

name: test-php-static-and-unit

on:
  workflow_call: ~
  workflow_dispatch: ~

permissions:
  contents: read

env:
  UNIT_TESTS_LOGS_SUB_DIR: build/unit_tests_logs

jobs:
  generate-php-versions:
    uses: ./.github/workflows/generate-php-versions.yml

  static-check-and-unit-tests:
    name: static check and unit tests
    runs-on: ubuntu-latest
    needs: generate-php-versions
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-php-versions.outputs.php-versions) }}
    env:
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@v6
      - name: Invoke test_php_static_and_unit.sh
        run: ./tools/test/test_php_static_and_unit.sh --php_versions "${PHP_VERSION}" --logs_dir "${PWD}/${{ env.UNIT_TESTS_LOGS_SUB_DIR }}"
      - uses: actions/upload-artifact@v6
        if: always()
        continue-on-error: false
        with:
          name: test_php_static_and_unit-log-${{ matrix.php-version }}
          path: |
            ${{ env.UNIT_TESTS_LOGS_SUB_DIR }}/*
