name: test

on:
  workflow_call: ~
  pull_request: ~
  push:
    branches:
      - main
  workflow_dispatch: ~

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-sources-license:
    uses: ./.github/workflows/test-sources-license.yml

  build:
    needs:
      - test-sources-license
    uses: ./.github/workflows/build.yml
    with:
      build_arch: all

  tests-phpt:
    needs:
      - build
    uses: ./.github/workflows/test-phpt.yml
    with:
      build_arch: all

  test-php-static-check:
    uses: ./.github/workflows/test-php-static-check.yml

  # The very last job to report whether the Workflow passed.
  # This will act as the Branch Protection gatekeeper
  ci:
    needs:
      - tests-phpt
      - test-php-static-check
    runs-on: ubuntu-latest
    steps:
      - name: report
        run: echo "CI workflow passed"
